[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< eu.supersede.if:eu.supersede.if.api >-----------------
[INFO] Building eu.supersede.if.api 0.4.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.um.ws.api.stub:jar:4.2.2 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.tenant.mgt.stub:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.um.ws.api:jar:4.2.2 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.user.api:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.user.core:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.utils:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for opensaml.wso2:opensaml2:jar:2.4.1.wso2v1 is missing, no dependency information available
[WARNING] The POM for org.wso2.andes.wso2:andes-client:jar:3.1.1 is missing, no dependency information available
[WARNING] The POM for org.apache.geronimo.specs.wso2:geronimo-jms_1.1_spec:jar:1.1.0.wso2v1 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.logging:jar:4.4.1 is missing, no dependency information available
[WARNING] The POM for org.wso2.securevault:org.wso2.securevault:jar:1.0.0-wso2v2 is missing, no dependency information available
[INFO] 
[INFO] --- pitest-maven:1.4.0:mutationCoverage (default-cli) @ eu.supersede.if.api ---
[INFO] Found plugin : JSON report plugin
[INFO] Found plugin : Produces a JSON file reporting mutation results aggregated by method and each method classfied according to its mutation status
[INFO] Found plugin : Generates an HTML document containing classes and methods with found testing issues
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Removes mutation in methods which are of no interest
[INFO] Found plugin : Static initializer code detector plugin
[INFO] Found plugin : Static initializer filter plugin
[INFO] Found plugin : Excluded annotations plugin
[INFO] Found plugin : Inlined finally block filter plugin
[INFO] Found plugin : Try with resources filter
[INFO] Found plugin : Implicit null check filter
[INFO] Found plugin : For each loop filter
[INFO] Found plugin : Logging calls filter
[INFO] Found plugin : Infinite for loop filter
[INFO] Found plugin : Long running iterator loop filter
[INFO] Found plugin : For loop counter filter
[INFO] Found plugin : Kotlin junk mutations filter
[INFO] Found plugin : Max mutations per class limit
[INFO] Found plugin : Equals shortcut equivalent mutant filter
[INFO] Found plugin : Trivial return vals equivalence filter
[INFO] Found plugin : Mutant export plugin
[INFO] Found shared classpath plugin : Engine for extreme mutation operators
[INFO] Found shared classpath plugin : Default mutation engine
[INFO] Found shared classpath plugin : JUnit plugin
[INFO] Found shared classpath plugin : TestNG plugin
[INFO] Adding eu.stamp-project:descartes to SUT classpath
[INFO] Adding org.pitest:pitest to SUT classpath
[INFO] Mutating from /home/stamp/Git/Supersede/integration/IF/API/eu.supersede.if.api/target/classes
[INFO] Defaulting target classes to match packages in build directory
2:45:52 PM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
2:45:53 PM PIT >> INFO : Sending 302 test classes to minion
2:45:53 PM PIT >> INFO : Sent tests to minion
2:45:53 PM PIT >> INFO : MINION : 2:45:53 PM PIT >> INFO : Checking environment

2:45:55 PM PIT >> INFO : MINION : 2:45:55 PM PIT >> INFO : Found  417 tests

2:45:55 PM PIT >> INFO : MINION : 2:45:55 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

2:45:55 PM PIT >> INFO : MINION : 2:45:55 PM PIT >> INFO : 417 tests received

2:45:56 PM PIT >> INFO : MINION : 2:45:56 PM PIT >> WARNING : More threads at end of test (5) eu.supersede.integration.api.adaptation.dashboard.proxies.test.AdaptationDashboardProxyTest than start. (4)

/-\|/-\2:56:14 PM PIT >> INFO : MINION : 2:56:14 PM PIT >> WARNING : More threads at end of test (6) eu.supersede.integration.api.analysis.proxies.test.AmplDataProviderProxyTest than start. (5)

|/-\|2:56:18 PM PIT >> INFO : MINION : 2:56:18 PM PIT >> WARNING : More threads at end of test (38) eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest than start. (6)

2:56:18 PM PIT >> INFO : MINION : 2:56:18 PM PIT >> WARNING : More threads at end of test (25) testLoginnull30_failAssert0null250_failAssert31null806_failAssert82(eu.supersede.integration.api.fe.test.AmplFrontendAuthenticationTest) than start. (24)

/-\|/-\|/-\|/-\|2:56:19 PM PIT >> INFO : MINION : 2:56:19 PM PIT >> WARNING : More threads at end of test (25) testLoginnull33_failAssert2litString224_failAssert72(eu.supersede.integration.api.fe.test.AmplFrontendAuthenticationTest) than start. (24)

/-\|/-\|/-\|3:00:00 PM PIT >> INFO : MINION : 3:00:00 PM PIT >> WARNING : More threads at end of test (48) testPublishAdaptionAlertMessage(eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest) than start. (22)

3:00:04 PM PIT >> INFO : MINION : 3:00:04 PM PIT >> WARNING : More threads at end of test (51) testPublishAlertMessage(eu.supersede.integration.api.pubsub.test.AlertPubSubTest) than start. (24)

/-\|/-3:00:09 PM PIT >> INFO : MINION : 3:00:09 PM PIT >> WARNING : More threads at end of test (48) testPublishEvolutionAlertMessage(eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest) than start. (24)

3:00:14 PM PIT >> INFO : MINION : 3:00:14 PM PIT >> WARNING : More threads at end of test (51) testPublishTextMessage(eu.supersede.integration.api.pubsub.test.PubSubTest) than start. (24)

\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|3:00:15 PM PIT >> INFO : MINION : 3:00:15 PM PIT >> WARNING : More threads at end of test (25) testGetReleaseByIdOfProjectById_mg13073_failAssert3236(eu.supersede.integration.api.replan.controller.proxies.test.AmplReplanControllerProxyTest) than start. (24)

/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/3:00:45 PM PIT >> INFO : MINION : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist

3:00:45 PM PIT >> INFO : MINION : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthe
3:00:45 PM PIT >> INFO : MINION : nticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.
3:00:45 PM PIT >> INFO : MINION : invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.
3:00:45 PM PIT >> INFO : MINION : junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

3:00:45 PM PIT >> INFO : MINION : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.juni
3:00:45 PM PIT >> INFO : MINION : t.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunn
3:00:45 PM PIT >> INFO : MINION : er$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit
3:00:45 PM PIT >> INFO : MINION : .internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnit
3:00:45 PM PIT >> INFO : MINION : TestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
	at org.pitest.testapi.execute.Pitest.exe
3:00:45 PM PIT >> INFO : MINION : cuteTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)
Caused by: org.apache
3:00:45 PM PIT >> INFO : MINION : .axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxi
3:00:45 PM PIT >> INFO : MINION : sOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.e
3:00:45 PM PIT >> INFO : MINION : xecute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:20
3:00:45 PM PIT >> INFO : MINION : 9)
	... 29 more

3:00:46 PM PIT >> INFO : MINION : 3:00:46 PM PIT >> WARNING : More threads at end of test (23) eu.supersede.integration.api.security.test.IFAuthenticationManagerTest than start. (22)

-\|/-\|/3:00:46 PM PIT >> INFO : Calculated coverage in 894 seconds.
3:00:47 PM PIT >> INFO : Created  110 mutation test units
stderr  : java.lang.IllegalArgumentException: Empty key
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
	at eu.supersede.integration.api.datastore.util.PasswordCrypt.decryptPassword(PasswordCrypt.java:87)
	at eu.supersede.integration.api.datastore.stderr  : proxies.IFDataStoreProxy.getSupersedePlatforms(IFDataStoreProxy.java:58)
	at eu.supersede.integration.federation.SupersedeFederation.<init>(SupersedeFederation.java:32)
	at eu.supersede.integration.federation.test.IFSupersedeFederationTest.setup(IFSupersedstderr  : eFederationTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.javastderr  : :43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runnersstderr  : .model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecustderr  : tor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.utstderr  : il.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
stderr  : javax.naming.ConfigurationException: Failed to parse entry: Not an AMQP URL A due to : Not an AMQP URL: A [Root exception is Not an AMQP URL A]
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createFactory(PropertiesFileInitialContextFactory.jastderr  : va:300)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createConnectionFactories(PropertiesFileInitialContextFactory.java:183)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.getInitialContext(PropertiesFileInitialContextFactory.jastderr  : va:149)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<istderr  : nit>(InitialContext.java:216)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.<init>(TopicMessageAgent.java:42)
	at eu.supersede.integration.api.pubsub.TopicSubscriber.<init>(TopicSubscriber.java:66)
	at eu.supersede.integration.api.pubsub.test.Pstderr  : ubSubTest.startSubscriber(PubSubTest.java:79)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.run(PubSubTest.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Not an AMQP URL A
	at org.wso2.andes.url.URLHelper.parseError(URLHelper.java:stderr  : 139)
	at org.wso2.andes.url.URLHelper.parseError(URLHelper.java:134)
	at org.wso2.andes.client.url.URLParser.parseURL(URLParser.java:155)
	at org.wso2.andes.client.url.URLParser.<init>(URLParser.java:42)
	at org.wso2.andes.client.AMQConnectionURL.<init>(AMstderr  : QConnectionURL.java:65)
	at org.wso2.andes.client.AMQConnectionFactory.<init>(AMQConnectionFactory.java:67)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createFactory(PropertiesFileInitialContextFactory.java:294)
	... 11 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUstderr  : ser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTestderr  : st(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAstderr  : ccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at ostderr  : rg.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:stderr  : 19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.stderr  : runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Role name: testRole in the system. Please pick another role name.
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.securstderr  : ity.IFUserStoreManager.addRole(IFUserStoreManager.java:155)
	at eu.supersede.integration.api.security.IFAuthenticationManager.addRole(IFAuthenticationManager.java:261)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUsestderr  : r(IFAuthenticationManagerTest.java:142)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.Frstderr  : ameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internalstderr  : .runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4Cstderr  : lassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRustderr  : nner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statstderr  : ements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(Adaptstderr  : edJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.stderr  : run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Role name: testRole in the system. Please pick another role name.
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	astderr  : t org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.descrstderr  : iption.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.addRole(RemoteUserStoreManagerServicstderr  : eStub.java:1613)
	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:153)
	... 28 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUstderr  : ser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTestderr  : st(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAstderr  : ccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at ostderr  : rg.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:stderr  : 19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.stderr  : runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.testderr  : st.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	stderr  : at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:5stderr  : 31)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2stderr  : .description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManastderr  : gerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.jastderr  : va:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lanstderr  : g.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMstderr  : ethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRstderr  : unner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(Parentstderr  : Runner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnestderr  : r$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.jstderr  : ava:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$Runnabstderr  : leAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFstderr  : aultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperastderr  : tion.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServicestderr  : Stub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:stderr  : 531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axisstderr  : 2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManstderr  : agerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperatistderr  : on$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOpstderr  : eration.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.sestderr  : curity.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.jastderr  : va:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lanstderr  : g.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMstderr  : ethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRstderr  : unner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(Parentstderr  : Runner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnestderr  : r$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.jstderr  : ava:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$Runnabstderr  : leAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFstderr  : aultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperastderr  : tion.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServicestderr  : Stub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Role name: testRole in the system. Please pick another role name.
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:155)
	at eu.supersede.integration.api.security.IFAuthentistderr  : cationManager.addRole(IFAuthenticationManager.java:261)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUser(IFAuthenticationManagerTest.java:142)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTestderr  : st.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMetstderr  : hodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallabstderr  : le.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.Expectstderr  : Exception.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJstderr  : Unit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.Parentstderr  : Runner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	atstderr  :  org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(Mustderr  : tationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Role nstderr  : ame: testRole in the system. Please pick another role name.
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOstderr  : nlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClstderr  : ient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.addRole(RemoteUserStoreManagerServiceStub.java:1613)
	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:15stderr  : 3)
	... 28 more
stderr  : org.wso2.andes.AMQConnectionFailureException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	astderr  : t org.wso2.andes.client.AMQConnectionFactory.createTopicConnection(AMQConnectionFactory.java:473)
stderr  : 	at eu.supersede.integration.api.pubsub.TopicMessageAgent.openTopicConnection(TopicMessageAgent.java:56)
	at eu.supersede.integration.api.pubsub.adaptation.AdaptationPublisher.<init>(AdaptationPublisher.java:30)
stderr  : 	at eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest.runPublisher(DMOptimizerProxyTest.java:63)
	at eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest.testOptimize(DMOptimizerProxyTest.java:113)
	at sun.reflect.NativeMethodAstderr  : ccessorImpl.invoke0(Native Method)
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runstderr  : Children(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at ostderr  : rg.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationteststderr  : .execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thstderr  : read.java:748)
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79)
	at org.wso2.andes.clistderr  : ent.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methostderr  : dReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.anstderr  : des.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:109)
	at org.wso2.andes.pool.Job.run(Job.java:153)
	at stderr  : java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutatiostderr  : ntest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.rstderr  : un(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperatstderr  : ionClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at stderr  : org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManastderr  : ger.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.stderr  : java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.jstderr  : unit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.javastderr  : :58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunstderr  : nerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	atstderr  :  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at ostderr  : rg.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAstderr  : xisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.stderr  : api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.tstderr  : est.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.rstderr  : unners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectExceptionstderr  : .java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.stderr  : junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.javstderr  : a:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRustderr  : nnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	astderr  : t java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at stderr  : org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInstderr  : AxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.wsstderr  : .api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(Parestderr  : ntRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pstderr  : itest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Exstderr  : ecutors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageCostderr  : ntext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	astderr  : t org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(Rstderr  : emoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Role name: testRole in the system. Please pick another role name.stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:155)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.addRole(IFAuthenticationManager.java:261)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUser(IFAuthenticationManagerTest.java:142)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerEstderr  : xecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javstderr  : a.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Role name: testRole in the system. Please picstderr  : k another role name.
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apachstderr  : e.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
stderr  : 	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.addRole(RemoteUserStoreManagerServiceStub.java:1613)
	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:153)
	... 28 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$stderr  : 0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Castderr  : nnot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
stderr  : 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationCliestderr  : nt.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.andes.AMQConnectionFailureException: not allowed [error code 530: not allowed]
stderr  : 	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createTopicConnection(AMQConnectionFactory.stderr  : java:473)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.openTopicConnection(TopicMessageAgent.java:56)
	at eu.supersede.integration.api.pubsub.adaptation.AdaptationPublisher.<init>(AdaptationPublisher.java:30)
	at eu.supersede.integration.api.dstderr  : m.proxies.test.DMOptimizerProxyTest.runPublisher(DMOptimizerProxyTest.java:63)
	at eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest.testOptimize(DMOptimizerProxyTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.Frstderr  : ameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internalstderr  : .runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRustderr  : nner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.stderr  : junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(Parentstderr  : Runner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambdastderr  : $createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andesstderr  : .client.AMQAuthenticationException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dstderr  : ispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at stderr  : org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQstderr  : MethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:109)
	at org.wso2.andes.pool.Job.run(Job.java:153)
	at java.util.concurrent.ThreadPoolExecutor.stderr  : runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
stderr  : java.lang.IllegalArgumentException: Missing argumentstderr  : 
stderr  : 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)stderr  : 
stderr  : 	at eu.supersede.integration.api.datastore.util.PasswordCrypt.decryptPassword(PasswordCrypt.java:87)stderr  : 
stderr  : 	at eu.supersede.integration.api.datastore.proxies.IFDataStoreProxy.getSupersedePlatforms(IFDataStoreProxy.java:58)stderr  : 
stderr  : 	at eu.supersede.integration.federation.SupersedeFederation.<init>(SupersedeFederation.java:32)stderr  : 
stderr  : 	at eu.supersede.integration.federation.test.IFSupersedeFederationTest.setup(IFSupersedeFederationTest.java:40)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefostderr  : res.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnistderr  : t.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTaskstderr  : .java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlystderr  : AxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(stderr  : OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integrastderr  : tion.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not existstderr  : 
stderr  : 	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)stderr  : 
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.destderr  : scription.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerstderr  : ServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpstderr  : l.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framewstderr  : orkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluatstderr  : e(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunnstderr  : er.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.Parestderr  : ntRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.jastderr  : va:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.stderr  : mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Tstderr  : hread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlstderr  : yOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:22stderr  : 9)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStstderr  : oreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.tstderr  : est.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.rstderr  : unners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.interstderr  : nal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnistderr  : t4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.rstderr  : un(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecoratstderr  : or.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.astderr  : pache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnstderr  : lyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClistderr  : ent.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.jastderr  : va:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUstderr  : ser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTestderr  : st(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAstderr  : ccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at ostderr  : rg.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:stderr  : 19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.stderr  : runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : java.lang.NullPointerException
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUser(IFAuthenticationManagerTest.java:141)stderr  : 
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImstderr  : pl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framestderr  : workMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluastderr  : te(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunstderr  : ner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.Parstderr  : entRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.jstderr  : ava:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.piteststderr  : .mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.stderr  : Thread.run(Thread.java:748)
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.jastderr  : va:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lanstderr  : g.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMstderr  : ethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRstderr  : unner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(Parentstderr  : Runner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnestderr  : r$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.jstderr  : ava:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$Runnabstderr  : leAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFstderr  : aultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperastderr  : tion.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServicestderr  : Stub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperatstderr  : ion$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOstderr  : peration.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.sstderr  : ecurity.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.andes.AMQConnectionFailureException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	astderr  : t org.wso2.andes.client.AMQConnectionFactory.createTopicConnection(AMQConnectionFactory.java:473)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.openTopicConnection(TopicMessageAgent.java:56)
	at eu.supersede.integration.api.pubsub.adaptation.Adstderr  : aptationPublisher.<init>(AdaptationPublisher.java:30)
	at eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest.runPublisher(DMOptimizerProxyTest.java:63)
	at eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest.testOptimize(DMOptistderr  : mizerProxyTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.javastderr  : :43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runnersstderr  : .model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4Classstderr  : Runner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunnerstderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUstderr  : ser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTestderr  : st(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAstderr  : ccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at ostderr  : rg.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:stderr  : 19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.stderr  : runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
stderr  : Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not existstderr  : 
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.stderr  : OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.stderr  : um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : java.lang.NullPointerExceptionstderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUser(IFAuthenticationManagerTest.java:141)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:stderr  : 531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axisstderr  : 2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManstderr  : agerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not existstderr  : 
stderr  : 	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)stderr  : 
stderr  : 	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)stderr  : 
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClistderr  : ent.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUstderr  : ser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTestderr  : st(IFAuthenticationManagerTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAstderr  : ccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at ostderr  : rg.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:stderr  : 19)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.stderr  : runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExstderr  : ecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at javastderr  : .util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apstderr  : ache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOpstderr  : erationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.sstderr  : tub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : java.lang.IllegalArgumentException: Provide a valid authentication tokenstderr  : 
stderr  : 	at org.springframework.util.Assert.notNull(Assert.java:115)stderr  : 
stderr  : 	at eu.supersede.integration.api.datastore.proxies.IFDataStoreProxy.getSupersedePlatforms(IFDataStoreProxy.java:47)stderr  : 
stderr  : 	at eu.supersede.integration.federation.SupersedeFederation.<init>(SupersedeFederation.java:32)stderr  : 
stderr  : 	at eu.supersede.integration.federation.test.IFSupersedeFederationTest.setup(IFSupersedeFederationTest.java:40)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : org.wso2.carbon.user.core.UserStoreException: Role name: testRole in the system. Please pick another role name.stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:155)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.addRole(IFAuthenticationManager.java:261)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.createTestUser(IFAuthenticationManagerTest.java:142)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:256)stderr  : 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflestderr  : ct.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.istderr  : nvokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.runners.ParentRunner.rstderr  : unLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.stderr  : java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evastderr  : luate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdaptstderr  : er.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Role name: testRole in the system. Please pick another role name.
	at org.apache.axis2stderr  : .util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClistderr  : ent.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.Remotestderr  : UserStoreManagerServiceStub.addRole(RemoteUserStoreManagerServiceStub.java:1613)
	at eu.supersede.integration.api.security.IFUserStoreManager.addRole(IFUserStoreManager.java:153)
	... 28 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not existstderr  : 
stderr  : 	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)stderr  : 
stderr  : 	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)stderr  : 
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClistderr  : ent.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : java.lang.NullPointerException
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:879)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at eu.supersede.integration.api.json.JsonUtils.deserializeJsonStstderr  : ringAsObject(JsonUtils.java:59)
	at eu.supersede.integration.api.pubsub.test.AlertPubSubTest$AlertMessageListener.onMessage(AlertPubSubTest.java:127)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:747)
	at org.wso2.astderr  : ndes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:721)
	at org.wso2.andes.client.AMQSession$Dispatcher.notifyConsumer(AMQSession.java:3537)
	at org.wso2.andes.client.AMQSession$Dispatcher.dispatchMessage(AMQSession.java:3477)
	at orgstderr  : .wso2.andes.client.AMQSession$Dispatcher.access$1200(AMQSession.java:3226)
	at org.wso2.andes.client.AMQSession.dispatch(AMQSession.java:3219)
	at org.wso2.andes.client.message.UnprocessedMessage.dispatch(UnprocessedMessage.java:54)
	at org.wso2.andes.cliestderr  : nt.AMQSession$Dispatcher.run(AMQSession.java:3399)
	at java.lang.Thread.run(Thread.java:748)
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefstderr  : ores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnstderr  : it.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTasstderr  : k.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlstderr  : yAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImplstderr  : (OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integrstderr  : ation.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : java.lang.NullPointerException
	at eu.supersede.integration.api.proxy.IFServiceProxy.getObjectsListForType(IFServiceProxy.java:110)
	at eu.supersede.integration.api.datastore.proxies.IFDataStoreProxy.getSupersedePlatforms(IFDataStoreProxy.java:53)
	at eu.sstderr  : upersede.integration.federation.SupersedeFederation.<init>(SupersedeFederation.java:32)
	at eu.supersede.integration.federation.test.IFSupersedeFederationTest.setup(IFSupersedeFederationTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native stderr  : Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.mstderr  : odel.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.istderr  : nternal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestderr  : stUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.costderr  : ncurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdaptstderr  : er.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFrostderr  : mMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.jastderr  : va:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.destderr  : leteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)stderr  : 
stderr  : Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not existstderr  : 
stderr  : 	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)stderr  : 
stderr  : 	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)stderr  : 
stderr  : 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)stderr  : 
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUsestderr  : r(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
stderr  : org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not existstderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)stderr  : 
stderr  : 	at eu.supersede.integration.api.security.test.IFAuthenticationManagerTest.throwUserDoesNotExistWhenDeleteUserTest(IFAuthenticationManagerTest.java:257)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)stderr  : 
stderr  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)stderr  : 
stderr  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)stderr  : 
stderr  : 	at java.lang.reflect.Method.invoke(Method.java:498)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)stderr  : 
stderr  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)stderr  : 
stderr  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)stderr  : 
stderr  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)stderr  : 
stderr  : 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)stderr  : 
stderr  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)stderr  : 
stderr  : 	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)stderr  : 
stderr  : 	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)stderr  : 
stderr  : 	at org.pitest.mutationtest.execute.MutationTimeoutDecorator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)stderr  : 
stderr  : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)stderr  : 
stderr  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)stderr  : 
stderr  : 	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Cannot delete user who is not exist
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperatistderr  : on$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOpstderr  : eration.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.deleteUser(RemoteUserStoreManagerServiceStub.java:1117)
	at eu.supersede.integration.api.sestderr  : curity.IFUserStoreManager.deleteUser(IFUserStoreManager.java:209)
	... 27 more
3:01:33 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : Exception in thread "Thread-14" stderr  : java.lang.NullPointerExceptionstderr  : 
stderr  : 	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.startSubscriber(EvolutionAlertPubSubTest.java:104)stderr  : 
stderr  : 	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.run(EvolutionAlertPubSubTest.java:82)
stderr  : 	at java.lang.Thread.run(Thread.java:748)
stderr  : javax.naming.ConfigurationException: Failed to parse entry: Not an AMQP URL  due to : Not an AMQP URL:  [Root exception is Not an AMQP URL ]
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createFactory(PropertiesFileInitialContextFactory.java:stderr  : 300)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createConnectionFactories(PropertiesFileInitialContextFactory.java:183)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.getInitialContext(PropertiesFileInitialContextFactory.java:stderr  : 149)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<initstderr  : >(InitialContext.java:216)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.<init>(TopicMessageAgent.java:42)
	at eu.supersede.integration.api.pubsub.TopicSubscriber.<init>(TopicSubscriber.java:66)
	at eu.supersede.integration.api.pubsub.test.PubSstderr  : ubTest.startSubscriber(PubSubTest.java:79)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.run(PubSubTest.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Not an AMQP URL 
	at org.wso2.andes.url.URLHelper.parseError(URLHelper.java:139)stderr  : 
	at org.wso2.andes.url.URLHelper.parseError(URLHelper.java:134)
	at org.wso2.andes.client.url.URLParser.parseURL(URLParser.java:155)
	at org.wso2.andes.client.url.URLParser.<init>(URLParser.java:42)
	at org.wso2.andes.client.AMQConnectionURL.<init>(AMQConstderr  : nectionURL.java:65)
	at org.wso2.andes.client.AMQConnectionFactory.<init>(AMQConnectionFactory.java:67)
	at org.wso2.andes.jndi.PropertiesFileInitialContextFactory.createFactory(PropertiesFileInitialContextFactory.java:294)
	... 11 more
3:02:07 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:07 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:08 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:09 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:11 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:16 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:18 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : Exception in thread "Thread-2" java.lang.NullPointerException
	at eu.supersede.integration.properties.IntegrationProperty.getMBConnection(IntegrationProperty.java:85)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.<init>(TopicMessageAgent.java:3stderr  : 7)
	at eu.supersede.integration.api.pubsub.TopicSubscriber.<init>(TopicSubscriber.java:66)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.startSubscriber(PubSubTest.java:79)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.run(PubSubTest.jastderr  : va:70)
	at java.lang.Thread.run(Thread.java:748)
stderr  : Exception in thread "Thread-2" java.lang.NullPointerException
	at eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest.startSubscriber(AdaptationAlertPubSubTest.java:93)
	at eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest.rstderr  : un(AdaptationAlertPubSubTest.java:78)
	at java.lang.Thread.run(Thread.java:748)
3:02:31 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : Exception in thread "Thread-44" java.lang.NullPointerException
	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.startSubscriber(EvolutionAlertPubSubTest.java:104)
	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.rustderr  : n(EvolutionAlertPubSubTest.java:82)
	at java.lang.Thread.run(Thread.java:748)
3:02:45 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:49 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:50 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:54 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : Exception in thread "Thread-2" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at eu.supersede.integration.api.pubsub.TopicMessageAgent.<init>(TopicMessageAgent.java:40)
	at eu.supersede.integration.api.pubsub.TopicSubscribestderr  : r.<init>(TopicSubscriber.java:66)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.startSubscriber(PubSubTest.java:79)
	at eu.supersede.integration.api.pubsub.test.PubSubTest.run(PubSubTest.java:70)
	at java.lang.Thread.run(Thread.java:748)
3:02:57 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:58 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:02:59 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:03:06 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : Exception in thread "Thread-2" java.lang.NullPointerException
	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.startSubscriber(EvolutionAlertPubSubTest.java:97)
	at eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest.run(stderr  : EvolutionAlertPubSubTest.java:82)
	at java.lang.Thread.run(Thread.java:748)
stderr  : com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.Objstderr  : ectMapper._initForReading(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at eu.supersede.integration.api.jsstderr  : on.JsonUtils.deserializeJsonStringAsObject(JsonUtils.java:59)
	at eu.supersede.integration.api.pubsub.test.AlertPubSubTest$AlertMessageListener.onMessage(AlertPubSubTest.java:127)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConstderr  : sumer.java:747)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:721)
	at org.wso2.andes.client.AMQSession$Dispatcher.notifyConsumer(AMQSession.java:3537)
	at org.wso2.andes.client.AMQSession$Dispatcher.dispatchMessagestderr  : (AMQSession.java:3477)
	at org.wso2.andes.client.AMQSession$Dispatcher.access$1200(AMQSession.java:3226)
	at org.wso2.andes.client.AMQSession.dispatch(AMQSession.java:3219)
	at org.wso2.andes.client.message.UnprocessedMessage.dispatch(UnprocessedMessage.jastderr  : va:54)
	at org.wso2.andes.client.AMQSession$Dispatcher.run(AMQSession.java:3399)
	at java.lang.Thread.run(Thread.java:748)
stderr  : com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.Objstderr  : ectMapper._initForReading(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at eu.supersede.integration.api.jsstderr  : on.JsonUtils.deserializeJsonStringAsObject(JsonUtils.java:59)
	at eu.supersede.integration.api.pubsub.test.AlertPubSubTest$AlertMessageListener.onMessage(AlertPubSubTest.java:127)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConstderr  : sumer.java:747)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:721)
	at org.wso2.andes.client.AMQSession$Dispatcher.notifyConsumer(AMQSession.java:3537)
	at org.wso2.andes.client.AMQSession$Dispatcher.dispatchMessagestderr  : (AMQSession.java:3477)
	at org.wso2.andes.client.AMQSession$Dispatcher.access$1200(AMQSession.java:3226)
	at org.wso2.andes.client.AMQSession.dispatch(AMQSession.java:3219)
	at org.wso2.andes.client.message.UnprocessedMessage.dispatch(UnprocessedMessage.jastderr  : va:54)
	at org.wso2.andes.client.AMQSession$Dispatcher.run(AMQSession.java:3399)
	at java.lang.Thread.run(Thread.java:748)
3:03:24 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:03:26 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:03:36 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:03:40 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:03:42 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:01 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:01 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:09 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
stderr  : com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'A': was expecting ('true', 'false' or 'null')
 at [Source: A; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.cstderr  : ore.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(Reastderr  : derBasedJsonParser.java:1903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.Objstderr  : ectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at eu.supersede.integration.api.json.JsonUtils.deserializeJsonStringAsObject(JsonUtils.java:59)
	at eu.supersede.integratistderr  : on.api.pubsub.test.AlertPubSubTest$AlertMessageListener.onMessage(AlertPubSubTest.java:127)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:747)
	at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessagstderr  : eConsumer.java:721)
	at org.wso2.andes.client.AMQSession$Dispatcher.notifyConsumer(AMQSession.java:3537)
	at org.wso2.andes.client.AMQSession$Dispatcher.dispatchMessage(AMQSession.java:3477)
	at org.wso2.andes.client.AMQSession$Dispatcher.access$1200(AMQSestderr  : ssion.java:3226)
	at org.wso2.andes.client.AMQSession.dispatch(AMQSession.java:3219)
	at org.wso2.andes.client.message.UnprocessedMessage.dispatch(UnprocessedMessage.java:54)
	at org.wso2.andes.client.AMQSession$Dispatcher.run(AMQSession.java:3399)
	at javstderr  : a.lang.Thread.run(Thread.java:748)
3:04:12 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:13 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:42 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
3:04:46 PM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
/stderr  : java.lang.NullPointerException
	at eu.supersede.integration.api.datastore.proxies.IFDataStoreProxy.getSupersedePlatforms(IFDataStoreProxy.java:57)
	at eu.supersede.integration.federation.SupersedeFederation.<init>(SupersedeFederation.java:32)
	at eu.supersstderr  : ede.integration.federation.test.IFSupersedeFederationTest.setup(IFSupersedeFederationTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.refstderr  : lect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.modestderr  : l.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunnerstderr  : .run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.mutationtest.execute.MutationTimeoutDecorstderr  : ator.lambda$createRunnable$0(MutationTimeoutDecorator.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-4:40:40 PM PIT >> INFO : Completed in 6887 seconds
================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : 14 minutes and 54 seconds
> build mutation tests : < 1 second
> run mutation analysis : 1 hours, 39 minutes and 51 seconds
--------------------------------------------------------------------------------
> Total  : 1 hours, 54 minutes and 47 seconds
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 631 mutations Killed 310 (49%)
>> Ran 6936 tests (10.99 tests per mutation)
================================================================================
- Mutators
================================================================================
> ""
>> Generated 37 Killed 14 (38%)
> KILLED 12 SURVIVED 1 TIMED_OUT 2 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 22 
--------------------------------------------------------------------------------
> 0
>> Generated 3 Killed 3 (100%)
> KILLED 3 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> 1
>> Generated 3 Killed 3 (100%)
> KILLED 2 SURVIVED 0 TIMED_OUT 1 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> "A"
>> Generated 37 Killed 13 (35%)
> KILLED 11 SURVIVED 2 TIMED_OUT 2 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 22 
--------------------------------------------------------------------------------
> void
>> Generated 79 Killed 32 (41%)
> KILLED 27 SURVIVED 9 TIMED_OUT 5 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 38 
--------------------------------------------------------------------------------
> null
>> Generated 438 Killed 225 (51%)
> KILLED 208 SURVIVED 5 TIMED_OUT 17 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 208 
--------------------------------------------------------------------------------
> false
>> Generated 12 Killed 6 (50%)
> KILLED 5 SURVIVED 0 TIMED_OUT 1 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 6 
--------------------------------------------------------------------------------
> true
>> Generated 12 Killed 5 (42%)
> KILLED 4 SURVIVED 1 TIMED_OUT 1 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 6 
--------------------------------------------------------------------------------
> empty
>> Generated 10 Killed 9 (90%)
> KILLED 9 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 1 
--------------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:54 h
[INFO] Finished at: 2018-11-14T16:40:40+01:00
[INFO] ------------------------------------------------------------------------
1824.23user 253.35system 1:54:54elapsed 30%CPU (0avgtext+0avgdata 1923732maxresident)k
96936inputs+1809616outputs (940major+22038830minor)pagefaults 0swaps
